version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "csharp-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-101wbg2nyurme"
s3_prefix = "csharp-demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=674881949129.dkr.ecr.us-east-1.amazonaws.com/samples"]
